//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAA_Task_9.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Auction_BAAEntities : DbContext
    {
        private static Auction_BAAEntities _context;
        public Auction_BAAEntities()
            : base("name=Auction_BAAEntities")
        {
        }
    
        public static Auction_BAAEntities GetContext()
        {
            if (_context == null)
            {
                _context = new Auction_BAAEntities();
            }
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Directory> Directories { get; set; }
        public virtual DbSet<Good> Goods { get; set; }
        public virtual DbSet<Sell> Sells { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
