//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAA_Task_9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sell
    {
        public int SellId { get; set; }
        public int CodeSellId { get; set; }
        public System.DateTime DateBargain { get; set; }
        public int StartingPrice { get; set; }
        public int FinalPrice { get; set; }
        public string SignOfSale { get; set; }
        public string BuyerLastName { get; set; }
    
        public virtual Good Good { get; set; }
    }
}
